Repository tult98/loca-sport, pull requests merged in 2024-02, with the labels that each got.

#6 docs: update README
  README.md
Labels: documentation

#8 fix: deploy next app to vercel
  @/apps/api/src/schema.gql
  apps/api/src/app.module.ts
  apps/web/project.json
Labels: enhancement

#10 fix: cannot build next & remove unnecessary files
  @/apps/api/src/schema.gql
  apps/api/src/app.module.ts
  apps/api/src/schema.gql
  apps/web/project.json
Labels: bug

#7 feat: Auth module
  apps/api/.env.example
  apps/api/src/app.module.ts
  apps/api/src/configs/type.ts
  apps/api/src/modules/auth/auth.module.ts
  apps/api/src/modules/auth/auth.resolver.ts
  apps/api/src/modules/auth/auth.service.ts
  apps/api/src/modules/auth/auth.type.ts
  apps/api/src/modules/auth/passport/jwt/jwt.decorator.ts
  apps/api/src/modules/auth/passport/jwt/jwt.guard.ts
  apps/api/src/modules/auth/passport/jwt/jwt.strategy.ts
  apps/api/src/modules/file/file.module.ts
  apps/api/src/modules/file/file.resolver.ts
  apps/api/src/modules/file/file.service.ts
  apps/api/src/modules/file/file.type.ts
  apps/api/src/modules/storage/cloudinary/cloudinary.module.ts
  apps/api/src/modules/storage/cloudinary/cloudinary.service.ts
  apps/api/src/modules/storage/storage.module.ts
  apps/api/src/modules/storage/storage.service.ts
  apps/api/src/modules/users/user.type.ts
  apps/api/src/modules/users/users.resolver.ts
  apps/api/src/prisma/schema.prisma
  apps/api/src/schema.gql
  apps/api/src/types/index.ts
  apps/api/src/utils/exception/http-exception.filter.ts
  apps/api/src/utils/helpers/formatter.ts
  apps/api/src/utils/helpers/index.ts
  apps/api/src/utils/helpers/regex.ts
  package.json
  yarn.lock
Labels: enhancement

#9 chore: reduce the CI runtime
  .github/workflows/ci.yml
  .gitignore
  .husky/pre-push
  apps/api/project.json
  nx.json
  package.json
  yarn.lock
Labels: enhancement

#13 feat: setup apollo client
  apps/api/src/schema.gql
  apps/web/.env
  apps/web/.env.example
  apps/web/src/app/layout.tsx
  apps/web/src/app/page.tsx
  apps/web/src/features/users/components/ListUser.tsx
  apps/web/src/features/users/index.ts
  apps/web/src/graphql/mutations.ts
  apps/web/src/graphql/queries.ts
  apps/web/src/libs/apollo-wrapper.tsx
  apps/web/src/libs/client.ts
  package.json
  yarn.lock
Labels: enhancement

#15 feat: setup `graphql-codegen`
  .github/workflows/ci.yml
  .gitignore
  README.md
  apps/api/project.json
  apps/web/codegen.yml
  apps/web/project.json
  apps/web/src/app/page.tsx
  apps/web/src/features/users/components/ListUser.tsx
  apps/web/src/graphql/mutations.ts
  apps/web/src/graphql/queries.gql
  apps/web/src/graphql/queries.ts
  nx.json
  package.json
  yarn.lock
Labels: enhancement

#16 feat: support for prisma seed db and nx
  .github/workflows/ci.yml
  apps/api/project.json
  apps/api/src/prisma/seed.ts
  package.json
  yarn.lock
Labels: enhancement
